# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: tod_local_ado_agent

steps:
- script: echo Running script to add s3 bucket and remove first s3 bucket.
  displayName: 'Announce what we are doing'

- script: python.exe C:\Users\todhi\OneDrive\work\python\boto\boto3\todboto3\use_boto_tools_to_create_bucket.py

#   displayName: 'Powershell script to call python boto script'
